import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import React from 'react'
import { RootState } from '../../src/app/store'
import { useSelector, useDispatch } from 'react-redux'
import { decrement, increment } from '../../src/features/counter/counterSlice'
import {fetchUserById} from '../../src/features/user/userSlice'

export default function Test() {
  const count = useSelector((state: RootState) => state.counter.value)
  const dispatch = useDispatch()
  const { users, loading, error } = useSelector((state) => state.users)

  const fetchOneUser = async (userId) => {
    try {
      const user = await dispatch(fetchUserById(userId)).unwrap()
      // showToast('success', `Fetched ${user.name}`)
    } catch (err) {
      // showToast('error', `Fetch failed: ${err.message}`)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js! </a>
        </h1>
        <div>
          <div>
            <button
              aria-label="Increment value"
              onClick={() => fetchOneUser(1)}
            >
              Increment
            </button>
            <span>{count}</span>
            <button
              aria-label="Decrement value"
              onClick={() => dispatch(decrement())}
            >
              Decrement
            </button>
          </div>
        </div>
      </main>
    </div>
  )
}
