import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { RootState } from '../src/app/store'
import * as abc from '../src/app/store'
// console.log("🚀 ~ abc", abc.RootState)
import { useSelector, useDispatch } from 'react-redux'
import { decrement, increment } from '../src/features/counter/counterSlice'
// export type Person = {
//     abc: number
//   }
//   console.log("🚀 ~ Home ~ Person", Person)
export default function Home() {
  
  const count = useSelector((state: RootState) => {
    const abd: RootState = state
    // console.log("🚀 ~ count ~ abd", increment.toString() )
    
    // console.log("🚀 ~ count ~ state", state)
    return state.counter.value
  })
  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <div>
        <div>
          <button
            aria-label="Increment value"
            onClick={() => dispatch(increment())}
          >
            Increment
          </button>
          <span>{count}</span>
          <button
            aria-label="Decrement value"
            onClick={() => dispatch(decrement())}
          >
            Decrement
          </button>
        </div>
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js! ffv </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
